# Generated by Django 4.0.3 on 2022-03-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('unit_size', models.PositiveIntegerField()),
                ('power', models.PositiveIntegerField()),
                ('prescription_required', models.BooleanField()),
                ('disease_category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.diseasecategory')),
                ('manufacturer_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('uses_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.use')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='uom_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.uom'),
        ),
    ]
